run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    golint:
        min-confidence: 0.9
    gocyclo:
        min-complexity: 15
    goimports:
        local-prefixes: github.com/banzaicloud/cloudinfo

linters:
    disable-all: true
    enable:
        - bodyclose
        - deadcode
        - dogsled
        - errcheck
        # - exportloopref
        - gochecknoinits
        - gofmt
        - goimports
        - golint
        - goprintffuncname
        - govet
        - ineffassign
        - misspell
        - nakedret
        - nolintlint
        - rowserrcheck
        - structcheck
        - typecheck
        - unused
        - varcheck

        # disabled for now
        # - dupl
        # - gochecknoglobals
        # - gocognit
        # - goconst
        # - gocritic
        # - gocyclo
        # - godot
        # - gosec
        # - gosimple
        # - lll
        # - prealloc
        # - scopelint
        # - staticcheck
        # - stylecheck
        # - unconvert
        # - unparam
        # - whitespace

        # unused
        # - depguard
        # - gomodguard

        # don't enable:
        # - asciicheck
        # - funlen
        # - godox
        # - goerr113
        # - gomnd
        # - interfacer
        # - maligned
        # - nestif
        # - testpackage
        # - wsl
