run:
    skip-dirs:
        - client

linters-settings:
    golint:
        min-confidence: 0.9

    gocyclo:
        min-complexity: 15

    goimports:
        local-prefixes: github.com/sagikazarmark/modern-go-application

linters:
    enable:
        - misspell
        - gofmt
        - golint
        - goimports

    disable:
        - errcheck
        - gas
        - megacheck
        - varcheck
    fast: false
