run:
    skip-dirs:
        - client

linters:
    enable-all: true
    disable:
        - funlen
        - errcheck
        - gas
        - megacheck
        - varcheck

        # TODO: Fix these
        - unparam
        - interfacer
        - dupl
        - lll
        - gocyclo
        - gocritic
        - unconvert
        - gochecknoglobals
        - nakedret
        - goconst
        - scopelint
        - prealloc

linters-settings:
    golint:
        # TODO: lower this value
        min-confidence: 0.9
    gocyclo:
        min-complexity: 15
    goimports:
        local-prefixes: github.com/banzaicloud/cloudinfo
