version: '3.1'

services:

  cloudinfo:
    image: banzaicloud/cloudinfo:${TAG:-test}
    restart: always
    environment:
    - PROVIDER=amazon
    - LOG_LEVEL=debug
    - ORACLE_CLI_CONFIG_LOCATION=/root/.oci/config
    ports:
    - 9090:9090
    - 8099:8099
    volumes:
    - ${HOME}/.aws:/root/.aws
    - ${HOME}/.oci:/root/.oci
