version: '3.1'

services:

  productinfo:
    image: banzaicloud/productinfo:${TAG:-names}
    restart: always
    environment:
    #    - AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEY_ID}
    #    - AWS_SECRET_ACCESS_KEY = ${AWS_SECRET_ACCESS_KEY}
    - PROVIDER=amazon
    ports:
    - 9090:9090
    volumes:
    - ${HOME}/.aws:/root/.aws
