version: '3.1'

services:

  productinfo:
    image: banzaicloud/productinfo:${TAG:-dev-local}
    restart: always
    environment:
    - PROVIDER=amazon oracle
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=
    - LOG_LEVEL=debug
    - ORACLE_CLI_CONFIG_LOCATION=/root/.oci/config
    ports:
    - 9090:9090
    volumes:
    - ${HOME}/.aws:/root/.aws
    - ${HOME}/.oci:/root/.oci
