// Code generated by go-swagger; DO NOT EDIT.

package continents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new continents API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for continents API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetContinents Returns the supported continents
*/
func (a *Client) GetContinents(params *GetContinentsParams) (*GetContinentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetContinentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getContinents",
		Method:             "GET",
		PathPattern:        "/continents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetContinentsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetContinentsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
