// Code generated by go-swagger; DO NOT EDIT.

package continents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/banzaicloud/cloudinfo/pkg/cloudinfo-client/models"
)

// GetContinentsReader is a Reader for the GetContinents structure.
type GetContinentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContinentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetContinentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetContinentsOK creates a GetContinentsOK with default headers values
func NewGetContinentsOK() *GetContinentsOK {
	return &GetContinentsOK{}
}

/*GetContinentsOK handles this case with default header values.

ContinentsResponse
*/
type GetContinentsOK struct {
	Payload models.ContinentsResponse
}

func (o *GetContinentsOK) Error() string {
	return fmt.Sprintf("[GET /continents][%d] getContinentsOK  %+v", 200, o.Payload)
}

func (o *GetContinentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
