// Code generated by go-swagger; DO NOT EDIT.

package continents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/banzaicloud/cloudinfo/pkg/cloudinfo-client/models"
)

// GetContinentsDataReader is a Reader for the GetContinentsData structure.
type GetContinentsDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContinentsDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetContinentsDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetContinentsDataOK creates a GetContinentsDataOK with default headers values
func NewGetContinentsDataOK() *GetContinentsDataOK {
	return &GetContinentsDataOK{}
}

/*GetContinentsDataOK handles this case with default header values.

ContinentsDataResponse
*/
type GetContinentsDataOK struct {
	Payload models.ContinentsDataResponse
}

func (o *GetContinentsDataOK) Error() string {
	return fmt.Sprintf("[GET /providers/{provider}/services/{service}/continents][%d] getContinentsDataOK  %+v", 200, o.Payload)
}

func (o *GetContinentsDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
