// Code generated by go-swagger; DO NOT EDIT.

package continents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContinentsParams creates a new GetContinentsParams object
// with the default values initialized.
func NewGetContinentsParams() *GetContinentsParams {

	return &GetContinentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContinentsParamsWithTimeout creates a new GetContinentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContinentsParamsWithTimeout(timeout time.Duration) *GetContinentsParams {

	return &GetContinentsParams{

		timeout: timeout,
	}
}

// NewGetContinentsParamsWithContext creates a new GetContinentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContinentsParamsWithContext(ctx context.Context) *GetContinentsParams {

	return &GetContinentsParams{

		Context: ctx,
	}
}

// NewGetContinentsParamsWithHTTPClient creates a new GetContinentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContinentsParamsWithHTTPClient(client *http.Client) *GetContinentsParams {

	return &GetContinentsParams{
		HTTPClient: client,
	}
}

/*GetContinentsParams contains all the parameters to send to the API endpoint
for the get continents operation typically these are written to a http.Request
*/
type GetContinentsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get continents params
func (o *GetContinentsParams) WithTimeout(timeout time.Duration) *GetContinentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get continents params
func (o *GetContinentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get continents params
func (o *GetContinentsParams) WithContext(ctx context.Context) *GetContinentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get continents params
func (o *GetContinentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get continents params
func (o *GetContinentsParams) WithHTTPClient(client *http.Client) *GetContinentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get continents params
func (o *GetContinentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetContinentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
