// Code generated by go-swagger; DO NOT EDIT.

package continents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContinentsDataParams creates a new GetContinentsDataParams object
// with the default values initialized.
func NewGetContinentsDataParams() *GetContinentsDataParams {
	var ()
	return &GetContinentsDataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContinentsDataParamsWithTimeout creates a new GetContinentsDataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContinentsDataParamsWithTimeout(timeout time.Duration) *GetContinentsDataParams {
	var ()
	return &GetContinentsDataParams{

		timeout: timeout,
	}
}

// NewGetContinentsDataParamsWithContext creates a new GetContinentsDataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContinentsDataParamsWithContext(ctx context.Context) *GetContinentsDataParams {
	var ()
	return &GetContinentsDataParams{

		Context: ctx,
	}
}

// NewGetContinentsDataParamsWithHTTPClient creates a new GetContinentsDataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContinentsDataParamsWithHTTPClient(client *http.Client) *GetContinentsDataParams {
	var ()
	return &GetContinentsDataParams{
		HTTPClient: client,
	}
}

/*GetContinentsDataParams contains all the parameters to send to the API endpoint
for the get continents data operation typically these are written to a http.Request
*/
type GetContinentsDataParams struct {

	/*Provider*/
	Provider string
	/*Service*/
	Service string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get continents data params
func (o *GetContinentsDataParams) WithTimeout(timeout time.Duration) *GetContinentsDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get continents data params
func (o *GetContinentsDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get continents data params
func (o *GetContinentsDataParams) WithContext(ctx context.Context) *GetContinentsDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get continents data params
func (o *GetContinentsDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get continents data params
func (o *GetContinentsDataParams) WithHTTPClient(client *http.Client) *GetContinentsDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get continents data params
func (o *GetContinentsDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProvider adds the provider to the get continents data params
func (o *GetContinentsDataParams) WithProvider(provider string) *GetContinentsDataParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the get continents data params
func (o *GetContinentsDataParams) SetProvider(provider string) {
	o.Provider = provider
}

// WithService adds the service to the get continents data params
func (o *GetContinentsDataParams) WithService(service string) *GetContinentsDataParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the get continents data params
func (o *GetContinentsDataParams) SetService(service string) {
	o.Service = service
}

// WriteToRequest writes these params to a swagger request
func (o *GetContinentsDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
