// Code generated by go-swagger; DO NOT EDIT.

package attributes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAttrValuesParams creates a new GetAttrValuesParams object
// with the default values initialized.
func NewGetAttrValuesParams() *GetAttrValuesParams {
	var ()
	return &GetAttrValuesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAttrValuesParamsWithTimeout creates a new GetAttrValuesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAttrValuesParamsWithTimeout(timeout time.Duration) *GetAttrValuesParams {
	var ()
	return &GetAttrValuesParams{

		timeout: timeout,
	}
}

// NewGetAttrValuesParamsWithContext creates a new GetAttrValuesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAttrValuesParamsWithContext(ctx context.Context) *GetAttrValuesParams {
	var ()
	return &GetAttrValuesParams{

		Context: ctx,
	}
}

// NewGetAttrValuesParamsWithHTTPClient creates a new GetAttrValuesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAttrValuesParamsWithHTTPClient(client *http.Client) *GetAttrValuesParams {
	var ()
	return &GetAttrValuesParams{
		HTTPClient: client,
	}
}

/*GetAttrValuesParams contains all the parameters to send to the API endpoint
for the get attr values operation typically these are written to a http.Request
*/
type GetAttrValuesParams struct {

	/*Attribute*/
	Attribute string
	/*Provider*/
	Provider string
	/*Region*/
	Region string
	/*Service*/
	Service string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get attr values params
func (o *GetAttrValuesParams) WithTimeout(timeout time.Duration) *GetAttrValuesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get attr values params
func (o *GetAttrValuesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get attr values params
func (o *GetAttrValuesParams) WithContext(ctx context.Context) *GetAttrValuesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get attr values params
func (o *GetAttrValuesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get attr values params
func (o *GetAttrValuesParams) WithHTTPClient(client *http.Client) *GetAttrValuesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get attr values params
func (o *GetAttrValuesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttribute adds the attribute to the get attr values params
func (o *GetAttrValuesParams) WithAttribute(attribute string) *GetAttrValuesParams {
	o.SetAttribute(attribute)
	return o
}

// SetAttribute adds the attribute to the get attr values params
func (o *GetAttrValuesParams) SetAttribute(attribute string) {
	o.Attribute = attribute
}

// WithProvider adds the provider to the get attr values params
func (o *GetAttrValuesParams) WithProvider(provider string) *GetAttrValuesParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the get attr values params
func (o *GetAttrValuesParams) SetProvider(provider string) {
	o.Provider = provider
}

// WithRegion adds the region to the get attr values params
func (o *GetAttrValuesParams) WithRegion(region string) *GetAttrValuesParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the get attr values params
func (o *GetAttrValuesParams) SetRegion(region string) {
	o.Region = region
}

// WithService adds the service to the get attr values params
func (o *GetAttrValuesParams) WithService(service string) *GetAttrValuesParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the get attr values params
func (o *GetAttrValuesParams) SetService(service string) {
	o.Service = service
}

// WriteToRequest writes these params to a swagger request
func (o *GetAttrValuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param attribute
	if err := r.SetPathParam("attribute", o.Attribute); err != nil {
		return err
	}

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	// path param region
	if err := r.SetPathParam("region", o.Region); err != nil {
		return err
	}

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
