// Code generated by go-swagger; DO NOT EDIT.

package attributes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/banzaicloud/productinfo/pkg/productinfo-client/models"
)

// GetAttributeValuesReader is a Reader for the GetAttributeValues structure.
type GetAttributeValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAttributeValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAttributeValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAttributeValuesOK creates a GetAttributeValuesOK with default headers values
func NewGetAttributeValuesOK() *GetAttributeValuesOK {
	return &GetAttributeValuesOK{}
}

/*GetAttributeValuesOK handles this case with default header values.

AttributeResponse
*/
type GetAttributeValuesOK struct {
	Payload *models.AttributeResponse
}

func (o *GetAttributeValuesOK) Error() string {
	return fmt.Sprintf("[GET /products/{provider}/{region}/{attribute}][%d] getAttributeValuesOK  %+v", 200, o.Payload)
}

func (o *GetAttributeValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AttributeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
