// Code generated by go-swagger; DO NOT EDIT.

package regions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/banzaicloud/cloudinfo/pkg/cloudinfo-client/models"
)

// GetRegionReader is a Reader for the GetRegion structure.
type GetRegionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRegionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRegionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRegionOK creates a GetRegionOK with default headers values
func NewGetRegionOK() *GetRegionOK {
	return &GetRegionOK{}
}

/*GetRegionOK handles this case with default header values.

GetRegionResp
*/
type GetRegionOK struct {
	Payload *models.GetRegionResp
}

func (o *GetRegionOK) Error() string {
	return fmt.Sprintf("[GET /providers/{provider}/services/{service}/regions/{region}][%d] getRegionOK  %+v", 200, o.Payload)
}

func (o *GetRegionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetRegionResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
