// Code generated by go-swagger; DO NOT EDIT.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProviderParams creates a new GetProviderParams object
// with the default values initialized.
func NewGetProviderParams() *GetProviderParams {
	var ()
	return &GetProviderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProviderParamsWithTimeout creates a new GetProviderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProviderParamsWithTimeout(timeout time.Duration) *GetProviderParams {
	var ()
	return &GetProviderParams{

		timeout: timeout,
	}
}

// NewGetProviderParamsWithContext creates a new GetProviderParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProviderParamsWithContext(ctx context.Context) *GetProviderParams {
	var ()
	return &GetProviderParams{

		Context: ctx,
	}
}

// NewGetProviderParamsWithHTTPClient creates a new GetProviderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProviderParamsWithHTTPClient(client *http.Client) *GetProviderParams {
	var ()
	return &GetProviderParams{
		HTTPClient: client,
	}
}

/*GetProviderParams contains all the parameters to send to the API endpoint
for the get provider operation typically these are written to a http.Request
*/
type GetProviderParams struct {

	/*Provider*/
	Provider string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get provider params
func (o *GetProviderParams) WithTimeout(timeout time.Duration) *GetProviderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get provider params
func (o *GetProviderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get provider params
func (o *GetProviderParams) WithContext(ctx context.Context) *GetProviderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get provider params
func (o *GetProviderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get provider params
func (o *GetProviderParams) WithHTTPClient(client *http.Client) *GetProviderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get provider params
func (o *GetProviderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProvider adds the provider to the get provider params
func (o *GetProviderParams) WithProvider(provider string) *GetProviderParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the get provider params
func (o *GetProviderParams) SetProvider(provider string) {
	o.Provider = provider
}

// WriteToRequest writes these params to a swagger request
func (o *GetProviderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
