// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProvidersParams creates a new GetProvidersParams object
// with the default values initialized.
func NewGetProvidersParams() *GetProvidersParams {

	return &GetProvidersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProvidersParamsWithTimeout creates a new GetProvidersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProvidersParamsWithTimeout(timeout time.Duration) *GetProvidersParams {

	return &GetProvidersParams{

		timeout: timeout,
	}
}

// NewGetProvidersParamsWithContext creates a new GetProvidersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProvidersParamsWithContext(ctx context.Context) *GetProvidersParams {

	return &GetProvidersParams{

		Context: ctx,
	}
}

// NewGetProvidersParamsWithHTTPClient creates a new GetProvidersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProvidersParamsWithHTTPClient(client *http.Client) *GetProvidersParams {

	return &GetProvidersParams{
		HTTPClient: client,
	}
}

/*GetProvidersParams contains all the parameters to send to the API endpoint
for the get providers operation typically these are written to a http.Request
*/
type GetProvidersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get providers params
func (o *GetProvidersParams) WithTimeout(timeout time.Duration) *GetProvidersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get providers params
func (o *GetProvidersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get providers params
func (o *GetProvidersParams) WithContext(ctx context.Context) *GetProvidersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get providers params
func (o *GetProvidersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get providers params
func (o *GetProvidersParams) WithHTTPClient(client *http.Client) *GetProvidersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get providers params
func (o *GetProvidersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetProvidersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
