// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetImagesParams creates a new GetImagesParams object
// with the default values initialized.
func NewGetImagesParams() *GetImagesParams {
	var ()
	return &GetImagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImagesParamsWithTimeout creates a new GetImagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImagesParamsWithTimeout(timeout time.Duration) *GetImagesParams {
	var ()
	return &GetImagesParams{

		timeout: timeout,
	}
}

// NewGetImagesParamsWithContext creates a new GetImagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetImagesParamsWithContext(ctx context.Context) *GetImagesParams {
	var ()
	return &GetImagesParams{

		Context: ctx,
	}
}

// NewGetImagesParamsWithHTTPClient creates a new GetImagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetImagesParamsWithHTTPClient(client *http.Client) *GetImagesParams {
	var ()
	return &GetImagesParams{
		HTTPClient: client,
	}
}

/*GetImagesParams contains all the parameters to send to the API endpoint
for the get images operation typically these are written to a http.Request
*/
type GetImagesParams struct {

	/*Gpu*/
	Gpu *string
	/*Provider*/
	Provider string
	/*Region*/
	Region string
	/*Service*/
	Service string
	/*Version*/
	Version *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get images params
func (o *GetImagesParams) WithTimeout(timeout time.Duration) *GetImagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get images params
func (o *GetImagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get images params
func (o *GetImagesParams) WithContext(ctx context.Context) *GetImagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get images params
func (o *GetImagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get images params
func (o *GetImagesParams) WithHTTPClient(client *http.Client) *GetImagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get images params
func (o *GetImagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGpu adds the gpu to the get images params
func (o *GetImagesParams) WithGpu(gpu *string) *GetImagesParams {
	o.SetGpu(gpu)
	return o
}

// SetGpu adds the gpu to the get images params
func (o *GetImagesParams) SetGpu(gpu *string) {
	o.Gpu = gpu
}

// WithProvider adds the provider to the get images params
func (o *GetImagesParams) WithProvider(provider string) *GetImagesParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the get images params
func (o *GetImagesParams) SetProvider(provider string) {
	o.Provider = provider
}

// WithRegion adds the region to the get images params
func (o *GetImagesParams) WithRegion(region string) *GetImagesParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the get images params
func (o *GetImagesParams) SetRegion(region string) {
	o.Region = region
}

// WithService adds the service to the get images params
func (o *GetImagesParams) WithService(service string) *GetImagesParams {
	o.SetService(service)
	return o
}

// SetService adds the service to the get images params
func (o *GetImagesParams) SetService(service string) {
	o.Service = service
}

// WithVersion adds the version to the get images params
func (o *GetImagesParams) WithVersion(version *string) *GetImagesParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get images params
func (o *GetImagesParams) SetVersion(version *string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetImagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Gpu != nil {

		// query param gpu
		var qrGpu string
		if o.Gpu != nil {
			qrGpu = *o.Gpu
		}
		qGpu := qrGpu
		if qGpu != "" {
			if err := r.SetQueryParam("gpu", qGpu); err != nil {
				return err
			}
		}

	}

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	// path param region
	if err := r.SetPathParam("region", o.Region); err != nil {
		return err
	}

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if o.Version != nil {

		// query param version
		var qrVersion string
		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := qrVersion
		if qVersion != "" {
			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
