// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AttributeResponse AttributeResponse holds attribute values
// swagger:model AttributeResponse
type AttributeResponse struct {

	// attribute name
	AttributeName string `json:"attributeName,omitempty"`

	// attribute values
	AttributeValues []float64 `json:"attributeValues"`
}

// Validate validates this attribute response
func (m *AttributeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AttributeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AttributeResponse) UnmarshalBinary(b []byte) error {
	var res AttributeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
