// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ContinentsResponse ContinentsResponse holds the list of available continents
// swagger:model ContinentsResponse
type ContinentsResponse []string

// Validate validates this continents response
func (m ContinentsResponse) Validate(formats strfmt.Registry) error {
	return nil
}
