// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetRegionPathParams GetRegionPathParams is a placeholder for the regions related route path parameters
// swagger:model GetRegionPathParams
type GetRegionPathParams struct {

	// in:path
	Provider string `json:"provider,omitempty"`

	// in:path
	Region string `json:"region,omitempty"`

	// in:path
	Service string `json:"service,omitempty"`
}

// Validate validates this get region path params
func (m *GetRegionPathParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetRegionPathParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetRegionPathParams) UnmarshalBinary(b []byte) error {
	var res GetRegionPathParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
