// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetProviderPathParams GetProviderPathParams is a placeholder for the providers related route path parameters
// swagger:model GetProviderPathParams
type GetProviderPathParams struct {

	// in:path
	Provider string `json:"provider,omitempty"`
}

// Validate validates this get provider path params
func (m *GetProviderPathParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetProviderPathParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetProviderPathParams) UnmarshalBinary(b []byte) error {
	var res GetProviderPathParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
