// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetImagesQueryParams GetImagesQueryParams is a placeholder for the get images query parameters
// swagger:model GetImagesQueryParams
type GetImagesQueryParams struct {

	// in:query
	Gpu string `json:"gpu,omitempty"`

	// in:query
	Version string `json:"version,omitempty"`
}

// Validate validates this get images query params
func (m *GetImagesQueryParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetImagesQueryParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetImagesQueryParams) UnmarshalBinary(b []byte) error {
	var res GetImagesQueryParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
