// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetProductDetailsParams GetProductDetailsParams is a placeholder for the get products route's path parameters
// swagger:model GetProductDetailsParams
type GetProductDetailsParams struct {

	// in:path
	Provider string `json:"provider,omitempty"`

	// in:path
	Region string `json:"region,omitempty"`
}

// Validate validates this get product details params
func (m *GetProductDetailsParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetProductDetailsParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetProductDetailsParams) UnmarshalBinary(b []byte) error {
	var res GetProductDetailsParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
