// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetAttributeValuesParams GetAttributeValuesParams is a placeholder for the get attribute values route's path parameters
// swagger:model GetAttributeValuesParams
type GetAttributeValuesParams struct {

	// in:path
	Attribute string `json:"attribute,omitempty"`

	// in:path
	Provider string `json:"provider,omitempty"`

	// in:path
	Region string `json:"region,omitempty"`
}

// Validate validates this get attribute values params
func (m *GetAttributeValuesParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAttributeValuesParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAttributeValuesParams) UnmarshalBinary(b []byte) error {
	var res GetAttributeValuesParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
