// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetRegionsParams GetRegionsParams is a placeholder for the get regions route's path parameters
// swagger:model GetRegionsParams
type GetRegionsParams struct {

	// in:path
	Provider string `json:"provider,omitempty"`
}

// Validate validates this get regions params
func (m *GetRegionsParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetRegionsParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetRegionsParams) UnmarshalBinary(b []byte) error {
	var res GetRegionsParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
