// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ProviderDescriber ProviderDescriber describes a provider
// swagger:model ProviderDescriber
type ProviderDescriber struct {

	// GetProvider returns the name of the provider
	GetProvider string `json:"GetProvider,omitempty"`
}

// Validate validates this provider describer
func (m *ProviderDescriber) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProviderDescriber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProviderDescriber) UnmarshalBinary(b []byte) error {
	var res ProviderDescriber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
