// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ProviderResponse ProviderResponse is the response used for the supported providers
// swagger:model ProviderResponse
type ProviderResponse struct {

	// GetProvider returns the name of the provider
	GetProvider string `json:"GetProvider,omitempty"`
}

// Validate validates this provider response
func (m *ProviderResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProviderResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProviderResponse) UnmarshalBinary(b []byte) error {
	var res ProviderResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
