// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ProviderResponse ProviderResponse is the response used for the supported providers
// swagger:model ProviderResponse
type ProviderResponse []string

// Validate validates this provider response
func (m ProviderResponse) Validate(formats strfmt.Registry) error {
	return nil
}
