// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ServiceDescriber ServiceDescriber represents a service; eg.: oke, eks
// Extend this interface with other operations if needed
// swagger:model ServiceDescriber
type ServiceDescriber struct {

	// GetName abstracts the name assembly for the service
	GetName string `json:"GetName,omitempty"`
}

// Validate validates this service describer
func (m *ServiceDescriber) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceDescriber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceDescriber) UnmarshalBinary(b []byte) error {
	var res ServiceDescriber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
