// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/banzaicloud/productinfo/pkg/productinfo-client/models"
)

// GetProductDetailsReader is a Reader for the GetProductDetails structure.
type GetProductDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProductDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProductDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProductDetailsOK creates a GetProductDetailsOK with default headers values
func NewGetProductDetailsOK() *GetProductDetailsOK {
	return &GetProductDetailsOK{}
}

/*GetProductDetailsOK handles this case with default header values.

ProductDetailsResponse
*/
type GetProductDetailsOK struct {
	Payload *models.ProductDetailsResponse
}

func (o *GetProductDetailsOK) Error() string {
	return fmt.Sprintf("[GET /products/{provider}/{region}][%d] getProductDetailsOK  %+v", 200, o.Payload)
}

func (o *GetProductDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProductDetailsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
