// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/banzaicloud/productinfo/pkg/productinfo-client/models"
)

// GetServicesReader is a Reader for the GetServices structure.
type GetServicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetServicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 503:
		result := NewGetServicesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServicesOK creates a GetServicesOK with default headers values
func NewGetServicesOK() *GetServicesOK {
	return &GetServicesOK{}
}

/*GetServicesOK handles this case with default header values.

ProductServiceResponse
*/
type GetServicesOK struct {
	Payload models.ProductServiceResponse
}

func (o *GetServicesOK) Error() string {
	return fmt.Sprintf("[GET /providers/{provider}/services][%d] getServicesOK  %+v", 200, o.Payload)
}

func (o *GetServicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServicesServiceUnavailable creates a GetServicesServiceUnavailable with default headers values
func NewGetServicesServiceUnavailable() *GetServicesServiceUnavailable {
	return &GetServicesServiceUnavailable{}
}

/*GetServicesServiceUnavailable handles this case with default header values.

ErrorResponse
*/
type GetServicesServiceUnavailable struct {
	Payload *models.ErrorResponse
}

func (o *GetServicesServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /providers/{provider}/services][%d] getServicesServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetServicesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
